### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by MikeTheToon** [MikeTheToon/Toontown-Crystal#15]
**If you ever feel like doing something on the list, even if you're not assigned and/or someone else is assigned, still feel free to help! Also, do not be afraid to add things to the list.**

## Bugs ##
- [ ] #49 District Reset Toon Parties
- [x] #24 Fix certain nametag fonts
- [ ] #33 Unseen fog in Bossbot Headquarters, regardless of already implementing
- [ ] #34 GM icons not working
- [x] #40 Changing resolution on the "Options" page; game/server crash
- [ ] #41 Messages from Tutorial Tom are not clickable
- [x] #53 Fix Wedding Cake- District Reset on First Cog Round of VP

## Features ##
- [ ] #35 New street 
- [ ] #36 New playground
- [ ] #39 Buy DDoS Protection
- [x] #41 Gifting 
- [x] #44 Change treasures in Toontown Central to provide +5 laff points
- [ ] #43 Rewrite the "District" page
- [ ] #52 Cow and Goat Toons

## Resources ##
- [ ] #8 New TTCY Theme Song
- [ ] #37 Launcher
- [ ] #38 Button for Content Packs on launcher
